MOTIVATION_CONTEXT = "motivation"
STUDY_CONTEXT = "study"
WORKOUT_CONTEXT = "workout"
SLEEP_CONTEXT = "sleep"
GAMING_CONTEXT = "gaming"

CONTEXTS_ARRAY = [MOTIVATION_CONTEXT, STUDY_CONTEXT, WORKOUT_CONTEXT, SLEEP_CONTEXT, GAMING_CONTEXT]
